version: "3.8"

services:
  bookstore-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bookstore-network

  # Gelecekte veritabanı eklemek için hazır
  # bookstore-db:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   container_name: bookstore-db
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=YourStrong@Passw0rd
  #     - MSSQL_PID=Express
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - bookstore-db-data:/var/opt/mssql
  #   restart: unless-stopped
  #   networks:
  #     - bookstore-network

networks:
  bookstore-network:
    driver: bridge
# volumes:
#   bookstore-db-data:
